# Generated by Django 3.1.5 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210728_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugs',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
