# Generated by Django 3.1.5 on 2021-07-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugs',
            new_name='slug',
        ),
    ]
